language: node_js
node_js:
    - "10.16.0"
install:
    - npm install
script: npm test

before_deploy:
    - npm run static
deploy:
    provider: pages
    on:
        branch: development
    skip_cleanup: true
    keep-history: true
    github_token: $GITHUB_TOKEN
