export enum TextTypes {
  Default = "Default",
  Bold = "Bold",
  Italic = "Italic",
  BoldItalic = "BoldItalic",
  Caption = "Caption",
  CaptionBold = "CaptionBold",
  CaptionItalic = "CaptionItalic",
  CaptionBoldItalic = "CaptionBoldItalic",
  Small = "Tag",
  SmallBold = "TagBold",
  SmallItalic = "TagItalic",
  SmallBoldItalic = "TagBoldItalic",
  Mini = "Mini",
  MiniBold = "MiniBold",
  MiniItalic = "MiniItalic",
  MiniBoldItalic = "MiniBoldItalic",
}
