export enum TextTypes {
  Default = "Default",
  Bold = "Bold",
  Italic = "Italic",
  BoldItalic = "BoldItalic",
  Caption = "Caption",
  CaptionBold = "CaptionBold",
  CaptionItalic = "CaptionItalic",
  CaptionBoldItalic = "CaptionBoldItalic",
  Small = "Small",
  SmallBold = "SmallBold",
  SmallItalic = "SmallItalic",
  SmallBoldItalic = "SmallBoldItalic",
  Mini = "Mini",
  MiniBold = "MiniBold",
  MiniItalic = "MiniItalic",
  MiniBoldItalic = "MiniBoldItalic",
}
