import React from "react";
import { StatusBadge } from "./StatusBadge";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  StatusBadge,
  "https://www.figma.com/design/qShodlfNCJHb8n03IFyApM/Main?node-id=53029-41267&m=dev",
  {
    props: {
      icon: figma.instance("Icon"),
      showIcon: figma.boolean("Show Icon"),
      label: figma.string("Label"),
      level: figma.enum("Level", {
        low: "low",
        medium: "medium",
        high: "high",
      }),
      type: figma.enum("Type", {
        informative: "informative",
        negative: "negative",
        neutral: "neutral",
        positive: "positive",
        recommendation: "recommendation",
        warning: "warning",
      }),
      colorMode: figma.enum("Color Mode", {
        light: "light",
        dark: "dark",
      }),
    },
    example: (props) => (
      <StatusBadge type={props.type}>{props.label}</StatusBadge>
    ),
  }
);
