export enum LogoColors {
  Default = "",
  UiBlack = "ui.black",
  UiWhite = "ui.white",
}

export enum LogoSizes {
  Default = "default",
  ExtraExtraSmall = "xxsmall",
  ExtraSmall = "xsmall",
  Small = "small",
  Medium = "medium",
  Large = "large",
}

export enum LogoNames {
  BrooklynPublicLibraryBlack = "logo_bpl_black",
  BrooklynPublicLibraryWhite = "logo_bpl_white",
  CleverColor = "logo_clever_color",
  CleverWhite = "logo_clever_white",
  LPAColor = "logo_lpa_color",
  LPABlack = "logo_lpa_black",
  LPAWhite = "logo_lpa_white",
  MyLibraryNYCBlack = "logo_mln_black",
  MyLibraryNYCWhite = "logo_mln_white",
  NYPLBlack = "logo_nypl_full_black",
  NYPLWhite = "logo_nypl_full_white",
  NYPLLionBlack = "logo_nypl_lion_black",
  NYPLLionWhite = "logo_nypl_lion_white",
  QueensPublicLibraryColor = "logo_qpl_color",
  QueensPublicLibraryBlack = "logo_qpl_black",
  QueensPublicLibraryWhite = "logo_qpl_white",
  QueensPublicLibraryAltBlack = "logo_qpl_alt_black",
  QueensPublicLibraryAltWhite = "logo_qpl_alt_white",
  SchomburgColor = "logo_schomburg_color",
  SchomburgBlack = "logo_schomburg_black",
  SchomburgWhite = "logo_schomburg_white",
  SchomburgCircleColor = "logo_schomburg_circle_color",
  SchomburgCircleBlack = "logo_schomburg_circle_black",
  SchomburgCircleWhite = "logo_schomburg_circle_white",
  SimplyEColor = "logo_simplye_color",
  SimplyEBlack = "logo_simplye_black",
  SimplyEWhite = "logo_simplye_white",
  SNFLBlack = "logo_snfl_black",
  SNFLWhite = "logo_snfl_white",
  TreasuresColor = "logo_treasures_color",
  TreasuresColorNegative = "logo_treasures_color_negative",
}
