import type { Meta, StoryObj } from "@storybook/react-vite";
import NewsletterSignup from "./NewsletterSignup";
declare const meta: Meta<typeof NewsletterSignup>;
export default meta;
type Story = StoryObj<typeof NewsletterSignup>;
export declare const WithControls: Story;
export declare const NewsletterSignupOnSubmitExample: Story;
export declare const DescriptionUsingJSXElements: Story;
export declare const CustomHeadings: Story;
export declare const ComponentStates: Story;
export declare const HightlightColors: Story;
