services:
  node:
    image: tugboatqa/httpd
    commands:
      build:
        - apt-get update
        - apt-get install nodejs
        - apt-get install npm
        - npm install -g npm@latest
        - npm run build-storybook:v0
        - ln -snf "${TUGBOAT_ROOT}/reservoir/v0" "${DOCROOT}"
