export type Villager = {
  name: string;
  species: string;
  gender: string;
  personality: string;
  hobby: string;
  birthday: string;
  catchphrase: string;
  favoriteSaying: string;
  favoriteSong: string;
  portrait: string;
  subtype?: string;
  style1?: string;
  style2?: string;
  color1?: string;
  color2?: string;
};
export const villagers: Villager[] = [
  {
    name: "Admiral",
    species: "Bird",
    gender: "Male",
    personality: "Cranky",
    subtype: "A",
    hobby: "Nature",
    birthday: "1/27",
    catchphrase: "aye aye",
    favoriteSong: "Steep Hill",
    favoriteSaying: "Only quitters give up.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlBrd06.png",
    style1: "Cool",
    style2: "Cool",
    color1: "Black",
    color2: "Blue",
  },
  {
    name: "Agent S",
    species: "Squirrel",
    gender: "Female",
    personality: "Peppy",
    subtype: "B",
    hobby: "Fitness",
    birthday: "7/2",
    catchphrase: "sidekick",
    favoriteSong: "Go K.K. Rider",
    favoriteSaying: "You gotta put the pedal to the metal!",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlSqu06.png",
    style1: "Active",
    style2: "Simple",
    color1: "Blue",
    color2: "Black",
  },
  {
    name: "Agnes",
    species: "Pig",
    gender: "Female",
    personality: "Big Sister",
    subtype: "A",
    hobby: "Play",
    birthday: "4/21",
    catchphrase: "snuffle",
    favoriteSong: "K.K. House",
    favoriteSaying: "You reap what you sow.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlPig17.png",
    style1: "Simple",
    style2: "Elegant",
    color1: "Pink",
    color2: "White",
  },
  {
    name: "Al",
    species: "Gorilla",
    gender: "Male",
    personality: "Lazy",
    subtype: "B",
    hobby: "Fitness",
    birthday: "10/18",
    catchphrase: "ayyyeee",
    favoriteSong: "Go K.K. Rider",
    favoriteSaying: "Life is a buffet. Always go back for seconds.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlGor08.png",
    style1: "Active",
    style2: "Active",
    color1: "Red",
    color2: "White",
  },
  {
    name: "Alfonso",
    species: "Alligator",
    gender: "Male",
    personality: "Lazy",
    subtype: "B",
    hobby: "Play",
    birthday: "6/9",
    catchphrase: "it'sa me",
    favoriteSong: "Forest Life",
    favoriteSaying: "Slow and steady wins the race.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlCrd00.png",
    style1: "Simple",
    style2: "Simple",
    color1: "Red",
    color2: "Blue",
  },
  {
    name: "Alice",
    species: "Koala",
    gender: "Female",
    personality: "Normal",
    subtype: "B",
    hobby: "Education",
    birthday: "8/19",
    catchphrase: "guvnor",
    favoriteSong: "Aloha K.K.",
    favoriteSaying: "Treat others as you would like to be treated.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlKal01.png",
    style1: "Cute",
    style2: "Cute",
    color1: "Red",
    color2: "Pink",
  },
  {
    name: "Alli",
    species: "Alligator",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Fashion",
    birthday: "11/8",
    catchphrase: "graaagh",
    favoriteSong: "K.K. Soul",
    favoriteSaying: "Think before you act.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlCrd01.png",
    style1: "Gorgeous",
    style2: "Elegant",
    color1: "Yellow",
    color2: "Brown",
  },
  {
    name: "Amelia",
    species: "Eagle",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Music",
    birthday: "11/19",
    catchphrase: "cuz",
    favoriteSong: "K.K. Condor",
    favoriteSaying:
      "Pampering yourself is as important as food, water, and shelter!",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlPbr01.png",
    style1: "Cool",
    style2: "Elegant",
    color1: "Black",
    color2: "White",
  },
  {
    name: "Anabelle",

    species: "Anteater",
    gender: "Female",
    personality: "Peppy",
    subtype: "B",
    hobby: "Fashion",
    birthday: "2/16",
    catchphrase: "snorty",
    favoriteSong: "Aloha K.K.",
    favoriteSaying: "Dance like no one's watching!",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlAnt03.png",
    style1: "Cute",
    style2: "Simple",
    color1: "Green",
    color2: "Blue",
  },
  {
    name: "Anchovy",
    species: "Bird",
    gender: "Male",
    personality: "Lazy",
    subtype: "B",
    hobby: "Play",
    birthday: "3/4",
    catchphrase: "chuurp",
    favoriteSong: "K.K. Ragtime",
    favoriteSaying: "Why do today what you can put off until tomorrow?",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlBrd02.png",
    style1: "Simple",
    style2: "Simple",
    color1: "Colorful",
    color2: "Orange",
  },
  {
    name: "Angus",
    species: "Bull",
    gender: "Male",
    personality: "Cranky",
    subtype: "B",
    hobby: "Fitness",
    birthday: "4/30",
    catchphrase: "macmoo",
    favoriteSong: "K.K. Calypso",
    favoriteSaying: "Even strong bulls cry.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlBul00.png",
    style1: "Cool",
    style2: "Cool",
    color1: "Red",
    color2: "Black",
  },
  {
    name: "Anicotti",
    species: "Mouse",
    gender: "Female",
    personality: "Peppy",
    subtype: "B",
    hobby: "Fashion",
    birthday: "2/24",
    catchphrase: "cannoli",
    favoriteSong: "Neapolitan",
    favoriteSaying: "The walls have ears.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlMus10.png",
    style1: "Simple",
    style2: "Elegant",
    color1: "Red",
    color2: "Pink",
  },
  {
    name: "Ankha",
    species: "Cat",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Nature",
    birthday: "9/22",
    catchphrase: "me meow",
    favoriteSong: "K.K. Bazaar",
    favoriteSaying: "All that glitters is not gold.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlCat19.png",
    style1: "Gorgeous",
    style2: "Simple",
    color1: "Colorful",
    color2: "Brown",
  },
  {
    name: "Annalisa",
    species: "Anteater",
    gender: "Female",
    personality: "Normal",
    subtype: "A",
    hobby: "Nature",
    birthday: "2/6",
    catchphrase: "gumdrop",
    favoriteSong: "King K.K.",
    favoriteSaying: "Home is where the heart is.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlAnt08.png",
    style1: "Elegant",
    style2: "Gorgeous",
    color1: "Red",
    color2: "Pink",
  },
  {
    name: "Annalise",
    species: "Horse",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Fashion",
    birthday: "12/2",
    catchphrase: "nipper",
    favoriteSong: "Aloha K.K.",
    favoriteSaying: "Let gossip go in one ear and out the other.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlHrs09.png",
    style1: "Elegant",
    style2: "Active",
    color1: "Blue",
    color2: "Purple",
  },
  {
    name: "Antonio",
    species: "Anteater",
    gender: "Male",
    personality: "Jock",
    subtype: "B",
    hobby: "Fitness",
    birthday: "10/20",
    catchphrase: "honk",
    favoriteSong: "K.K. Ragtime",
    favoriteSaying: "Always go for the burn!",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlAnt01.png",
    style1: "Simple",
    style2: "Simple",
    color1: "Aqua",
    color2: "Blue",
  },
  {
    name: "Apollo",
    species: "Eagle",
    gender: "Male",
    personality: "Cranky",
    subtype: "B",
    hobby: "Music",
    birthday: "7/4",
    catchphrase: "pah",
    favoriteSong: "K.K. Rock",
    favoriteSaying: "What goes up must come down.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlPbr00.png",
    style1: "Cool",
    style2: "Simple",
    color1: "Black",
    color2: "Black",
  },
  {
    name: "Apple",
    species: "Hamster",
    gender: "Female",
    personality: "Peppy",
    subtype: "A",
    hobby: "Play",
    birthday: "9/24",
    catchphrase: "cheekers",
    favoriteSong: "I Love You",
    favoriteSaying: "One rotten apple spoils the barrel.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlHam01.png",
    style1: "Cute",
    style2: "Simple",
    color1: "Colorful",
    color2: "Red",
  },
  {
    name: "Astrid",
    species: "Kangaroo",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Music",
    birthday: "9/8",
    catchphrase: "my pet",
    favoriteSong: "K.K. Gumbo",
    favoriteSaying: "The apple doesn't fall far from the tree.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlKgr05.png",
    style1: "Cool",
    style2: "Active",
    color1: "Black",
    color2: "Colorful",
  },
  {
    name: "Audie",
    species: "Wolf",
    gender: "Female",
    personality: "Peppy",
    subtype: "A",
    hobby: "Fitness",
    birthday: "8/31",
    catchphrase: "foxtrot",
    favoriteSong: "K.K. Island",
    favoriteSaying:
      "Be the kind of person your future self won't regret having been.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlWol12..png",
    style1: "Cute",
    style2: "Active",
    color1: "Green",
    color2: "White",
  },
  {
    name: "Aurora",
    species: "Penguin",
    gender: "Female",
    personality: "Normal",
    subtype: "B",
    hobby: "Education",
    birthday: "1/27",
    catchphrase: "b-b-baby",
    favoriteSong: "Stale Cupcakes",
    favoriteSaying: "Always keep your cool.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlPgn00.png",
    style1: "Cute",
    style2: "Elegant",
    color1: "Pink",
    color2: "Red",
  },
  {
    name: "Ava",
    species: "Chicken",
    gender: "Female",
    personality: "Normal",
    subtype: "B",
    hobby: "Music",
    birthday: "4/28",
    catchphrase: "beaker",
    favoriteSong: "K.K. Love Song",
    favoriteSaying: "Early to bed, early to rise.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlChn05.png",
    style1: "Elegant",
    style2: "Cute",
    color1: "Red",
    color2: "Gray",
  },
  {
    name: "Avery",
    species: "Eagle",
    gender: "Male",
    personality: "Cranky",
    subtype: "B",
    hobby: "Music",
    birthday: "2/22",
    catchphrase: "skree-haw",
    favoriteSong: "K.K. Condor",
    favoriteSaying: "What goes around comes around.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlPbr05.png",
    style1: "Simple",
    style2: "Gorgeous",
    color1: "Orange",
    color2: "Brown",
  },
  {
    name: "Axel",
    species: "Elephant",
    gender: "Male",
    personality: "Jock",
    subtype: "B",
    hobby: "Fitness",
    birthday: "3/23",
    catchphrase: "WHONK",
    favoriteSong: "K.K. Dixie",
    favoriteSaying: "Do not compare a fly with an elephant.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlElp06.png",
    style1: "Active",
    style2: "Simple",
    color1: "Green",
    color2: "White",
  },
  {
    name: "Baabara",
    species: "Sheep",
    gender: "Female",
    personality: "Snooty",
    subtype: "B",
    hobby: "Fashion",
    birthday: "3/28",
    catchphrase: "daahling",
    favoriteSong: "K.K. Cruisin'",
    favoriteSaying: "Don't just follow the flock.",
    portrait: "https://acnhcdn.com/latest/NpcBromide/NpcNmlShp01.png",
    style1: "Gorgeous",
    style2: "Elegant",
    color1: "Purple",
    color2: "Blue",
  },
];
