const iconNames = [
  "accessibilityFull",
  "accessibilityPartial",
  "actionCheckCircle",
  "actionCheckCircleFilled",
  "actionExit",
  "actionHelpDefault",
  "actionHelpOutline",
  "actionLaunch",
  "actionPower",
  "actionRegistration",
  "actionSettings",
  "alertNotificationImportant",
  "alertWarningFilled",
  "alertWarningOutline",
  "arrow",
  "building",
  "check",
  "clock",
  "close",
  "decorativeEnvelope",
  "decorativeLibraryCard",
  "decorativeShoppingBag",
  "download",
  "errorFilled",
  "errorOutline",
  "fileTypeAudio",
  "fileTypeDoc",
  "fileTypeGenericDoc",
  "fileTypeImage",
  "fileTypePdf",
  "fileTypeSpreadsheet",
  "fileTypeVideo",
  "headset",
  "legacyAccountFilled",
  "legacyAccountUnfilled",
  "legacySocialFacebook",
  "legacySocialInstagram",
  "legacySocialTwitter",
  "legacySocialYoutube",
  "locator",
  "minus",
  "plus",
  "search",
  "socialFacebook",
  "socialInstagram",
  "socialPinterest",
  "socialSoundCloud",
  "socialTumblr",
  "socialTwitter",
  "socialYoutube",
  "speakerNotes",
  "utilityAccountFilled",
  "utilityAccountUnfilled",
  "utilityHamburger",
  "utilitySearch",
] as const;

export const getIconNames = () => iconNames;

export default iconNames;
