const iconColors = [
  "ui.black",
  "ui.white",
  "brand.primary",
  "brand.secondary",
  "ui.error.primary",
  "ui.error.secondary",
  "ui.status.primary",
  "ui.status.secondary",
  "ui.success.primary",
  "ui.success.secondary",
  "ui.warning.primary",
  "ui.warning.secondary",
  "section.blogs.primary",
  "section.blogs.secondary",
  "section.books-and-more.primary",
  "section.books-and-more.secondary",
  "section.education.primary",
  "section.education.secondary",
  "section.locations.primary",
  "section.locations.secondary",
  "section.research.primary",
  "section.research.secondary",
  "section.research-library.lpa",
  "section.research-library.schomburg",
  "section.research-library.schwartzman",
  "section.whats-on.primary",
  "section.whats-on.secondary",
  "dark.ui.error.primary",
  "dark.ui.error.secondary",
  "dark.ui.status.primary",
  "dark.ui.status.secondary",
  "dark.ui.success.primary",
  "dark.ui.success.secondary",
  "dark.ui.warning.primary",
  "dark.ui.warning.secondary",
] as const;

export const getIconColors = () => iconColors;

export default iconColors;
